# coding=utf-8
NOMBRES = [
('Arquitectura de Computadores', 'DAC', '159'),
('Ciencia de los Materiales e Ingeniería Metalúrgica', 'CMEM', '164'),
('Ciencia e Ingeniería Náuticas', 'CEN', '315'),
('Composición Arquitectónica', 'CA', '173'),
('Construcciones Arquitectónicas I', 'CA1', '182'),
('Construcciones Arquitectónicas II', 'CA2', '186'),
('Diseño y Programación de Sistemas Electrónicos', 'DIPSE', '118'),
('Estadística e Investigación Operativa', 'EIO', '227'),
('Estructuras en la Arquitectura', 'EA', '231'),
('Expresión Gráfica Arquitectónica I', 'EGA1', '239'),
('Expresión Gráfica Arquitectónica II', 'EGA2', '242'),
('Expresión Gráfica en la Ingeniería', 'EGE', '236'),
('Física Aplicada', 'FA', '249'),
('Física e Ingeniería Nuclear', 'FEN', '250'),
('Infraestructura del Transporte y del Territorio', 'ITT', '252'),
('Ingeniería Agroalimentaria y Biotecnología', 'DEAB', '321'),
('Ingeniería de la Construcción', 'EC', '188'),
('Ingeniería de Servicios y Sistemas de Información ', 'ESSI', '118'),
('Ingeniería de Sistemas, Automática e Informática Industrial', 'ESAII', '191'),
('Ingeniería del Terreno, Cartográfica y Geofísica', 'ETCG', '204'),
('Ingeniería Eléctrica', 'DEE', '210'),
('Ingeniería Electrónica', 'EEL', '399'),
('Ingeniería Hidráulica, Marítima y Ambiental', 'EHMA', '211'),
('Ingeniería Mecánica', 'EM', '212'),
('Ingeniería Minera y Recursos Naturales', 'EMRN', '313'),
('Ingeniería Química', 'EQ', '217'),
('Ingeniería Telemática', 'ENTEL) )', '318'),
('Ingeniería Textil y Papelera', 'DETIP', '221'),
('Lenguajes y Sistemas Informáticos', 'LSI', '254'),
('Máquinas y Motores Térmicos', 'MMT', '274'),
('Matemática Aplicada I', 'MA1', '275'),
('Matemática Aplicada II', 'MA2', '277'),
('Matemática Aplicada III', 'MA3', '278'),
('Matemática Aplicada IV', 'MA4', '317'),
('Mecánica de Fluidos', 'MF', '284'),
('Óptica y Optometría', 'OO', '287'),
('Organización de Empresas', 'OE', '289'),
('Proyectos Arquitectónicos', 'PA', '290'),
('Proyectos en la Ingeniería', 'PE', '306'),
('Resistencia de Materiales y Estructuras en la Ingeniería', 'RMEE', '307'),
('Teoría de la Señal y Comunicaciones', 'TSC', '309'),
('Urbanismo y Ordenación del Territorio', 'UOT', '311')
]

URL_UPC = 'http://www.upc.edu/unitat/fitxa_unitat.php?id_unitat={0}'