# coding=utf-8
ESTUDIOS = [
    ('Grado en Administración y Dirección de Empresas', 'Barcelona',
     'grados/administracion-y-direccion-de-empresas-barcelona'),
    ('Grado en Administración y Dirección de Empresas', 'Terrassa',
     'grados/administracion-y-direccion-de-empresas-terrassa'),
    ('Grado en Ciencias Culinarias y Gastronómicas', 'Castelldefels', 'ESAB',
     'grados/ciencias-culinarias-y-gastronomicas-interuniversitario-ub-upc-castelldefels-esab'),
    ('Grado en Ciencias y Tecnologías de la Edificación', 'Barcelona', 'EPSEB',
     'grados/ciencias-y-tecnologias-de-la-edificacion-barcelona-epseb'),
    ('Grado en Ciencias y Tecnologías de Telecomunicación', 'Barcelona', 'ETSETB',
     'grados/ciencias-y-tecnologias-de-telecomunicacion-barcelona-etsetb'),
    ('Grado en Diseño y Desarrollo de Videojuegos', 'Terrassa', 'CITM',
     'grados/diseno-y-desarrollo-de-videojuegos-terrassa-citm'),
    ('Grado en Economia-Estadística', 'Barcelona', 'FME',
     'grados/economia-estadistica-doble-titulacion-interuniversitaria-upc-ub-barcelona-fme'),
    ('Grado en Estadística', 'Barcelona', 'FME',
     'grados/estadistica-interuniversitario-ub-upc-barcelona-fme'),
    ('Grado en Estudios de Arquitectura', 'Barcelona', 'ETSAB', 'grados/estudios-de-arquitectura-barcelona-etsab'),
    ('Grado en Estudios de Arquitectura', 'Sant Cugat del Vallès', 'ETSAV',
     'grados/estudios-de-arquitectura-sant-cugat-del-valles-etsav'),
    (
        'Grado en Fotografía y Creación Digital', 'Terrassa', 'CITM',
        'grados/fotografia-y-creacion-digital-terrassa-citm'),
    ('Grado en Ingeniería Agrícola', 'Castelldefels', 'ESAB', 'grados/ingenieria-agricola-castelldefels-esab'),
    ('Grado en Ingeniería Agroambiental y del Paisaje', 'Castelldefels', 'ESAB',
     'grados/ingenieria-agroambiental-y-del-paisaje-castelldefels-esab'),
    ('Grado en Ingeniería Alimentaria', 'Castelldefels', 'ESAB', 'grados/ingenieria-alimentaria-castelldefels-esab'),
    ('Grado en Ingeniería Biomédica', 'Barcelona', 'EUETIB', 'grados/ingenieria-biomedica-barcelona-euetib'),
    ('Grado en Ingeniería Civil', 'Barcelona', 'ETSECCPB', 'grados/ingenieria-civil-barcelona-etseccpb'),
    ('Grado en Ingeniería de Aeronavegación', 'Castelldefels', 'EETAC',
     'grados/ingenieria-de-aeronavegacion-castelldefels-eetac'),
    ('Grado en Ingeniería de Aeropuertos', 'Castelldefels', 'EETAC',
     'grados/ingenieria-de-aeropuertos-castelldefels-eetac'),
    ('Grado en Ingeniería de Diseño Industrial y Desarrollo del Producto', 'Vilanova i la Geltrú', 'EPSEVG',
     'grados/ingenieria-de-diseno-industrial-y-desarrollo-del-producto-vilanova-i-la-geltru-epsevg'),
    ('Grado en Ingeniería de la Construcción', 'Barcelona', 'ETSECCPB',
     'grados/ingenieria-de-la-construccion-barcelona-etseccpb'),
    ('Grado en Ingeniería de la Energía', 'Barcelona', 'EUETIB', 'grados/ingenieria-de-la-energia-barcelona-euetib'),
    ('Grado en Ingeniería de Materiales', 'Barcelona', 'ETSEIB', 'grados/ingenieria-de-materiales-barcelona-etseib'),
    ('Grado en Ingeniería de Recursos Energéticos y Mineros', 'Manresa', 'EPSEM',
     'grados/ingenieria-de-recursos-energeticos-y-mineros-manresa-epsem'),
    ('Grado en Ingeniería de Sistemas Audiovisuales', 'Barcelona', 'ETSETB',
     'grados/ingenieria-de-sistemas-audiovisuales-barcelona-etsetb'),
    ('Grado en Ingeniería de Sistemas Biológicos', 'Castelldefels', 'ESAB',
     'grados/ingenieria-de-sistemas-de-telecomunicacion-castelldefels-eetac'),
    ('Grado en Ingeniería de Sistemas de Telecomunicación', 'Barcelona', 'ETSETB',
     'grados/ingenieria-de-sistemas-de-telecomunicacion-barcelona-etsetb'),
    ('Grado en Ingeniería de Sistemas Electrónicos', 'Barcelona', 'ETSETB',
     'grados/ingenieria-de-sistemas-electronicos-barcelona-etsetb'),
    ('Grado en Ingeniería de Sistemas TIC', 'Manresa', 'EPSEM', 'grados/ingenieria-de-sistemas-tic-manresa-epsem'),
    ('Grado en Ingeniería de Tecnología y Diseño Textil', 'Terrassa', 'EET',
     'grados/ingenieria-de-tecnologia-y-diseno-textil-terrassa-eet'),
    ('Grado en Ingeniería Eléctrica', 'Terrassa', 'EET', 'grados/ingenieria-electrica-terrassa-eet'),
    ('Grado en Ingeniería Electrónica Industrial y Automática', 'Barcelona', 'EUETIB',
     'grados/ingenieria-electronica-industrial-y-automatica-terrassa-eet'),
    ('Grado en Ingeniería en Organización Industrial', 'Igualada', 'EEI',
     'grados/ingenieria-en-organizacion-industrial-igualada-eei'),
    ('Grado en Ingeniería en Sistemas y Tecnología Naval', 'Barcelona', 'FNB',
     'grados/ingenieria-en-sistemas-y-tecnologia-naval-barcelona-fnb'),
    ('Grado en Ingeniería en Tecnologías Aeroespaciales', 'Terrassa', 'ETSEIAT',
     'grados/ingenieria-en-tecnologias-aeroespaciales-terrassa-etseiat'),
    ('Grado en Ingeniería en Tecnologías Industriales', 'Barcelona', 'ETSEIB',
     'grados/ingenieria-en-tecnologias-industriales-barcelona-etseib'),
    ('Grado en Ingeniería en Vehículos Aeroespaciales', 'Terrassa', 'ETSEIAT',
     'grados/ingenieria-en-vehiculos-aeroespaciales-terrassa-etseiat'),
    ('Grado en Ingeniería Física', 'Barcelona', 'ETSETB', 'grados/ingenieria-fisica-barcelona-etsetb'),
    ('Grado en Ingeniería Geológica', 'Barcelona', 'ETSECCPB',
     'grados/ingenieria-geologica-interuniversitario-upc-ub-barcelona-etseccpb'),
    ('Grado en Ingeniería Geomática y Topografía', 'Barcelona', 'EPSEB',
     'grados/ingenieria-geomatica-y-topografia-barcelona-epseb'),
    ('Grado en Ingeniería Informática: Computación',
     'Barcelona', 'FIB', 'grados/ingenieria-informatica-barcelona-fib'),
    ('Grado en Ingeniería Informática: Ingeniería de Software',
     'Barcelona', 'FIB', 'grados/ingenieria-informatica-barcelona-fib'),
    ('Grado en Ingeniería Informática: Tecnologías de la información',
     'Barcelona', 'FIB', 'grados/ingenieria-informatica-barcelona-fib'),
    ('Grado en Ingeniería Informática: Ingeniería de computadores',
     'Barcelona', 'FIB', 'grados/ingenieria-informatica-barcelona-fib'),
    ('Grado en Ingeniería Informática: Sistemas de la información',
     'Barcelona', 'FIB', 'grados/ingenieria-informatica-barcelona-fib'),
    ('Grado en Ingeniería Marina', 'Barcelona', 'FNB',
     'grados/ingenieria-marina-barcelona-fnb'),
    ('Grado en Ingeniería Mecánica', 'Barcelona', 'EUETIB', 'grados/ingenieria-mecanica-barcelona-euetib'),
    ('Grado en Ingeniería Náutica y Transporte Marítimo',
     'Barcelona', 'FNB', 'grados/ingenieria-nautica-y-transporte-maritimo-barcelona-fnb'),
    ('Grado en Ingeniería Química', 'Barcelona', 'EUETIB', 'grados/ingenieria-quimica-barcelona-euetib'),
    ('Grado en Ingeniería Telemática', 'Barcelona', 'ETSETB', 'grados/ingenieria-telematica-barcelona-etsetb'),
    ('Grado en Márketing y Comunicación Digital', 'Terrassa', 'grados/marketing-y-comunicacion-digital-terrassa'),
    ('Grado en Matemáticas', 'Barcelona', 'FME', 'grados/matematicas-barcelona-fme'),
    ('Grado en Multimedia', 'Terrassa', 'CITM', 'grados/multimedia-terrassa-citm'),
    ('Grado en Óptica y Optometría', 'Terrassa', 'FOOT', 'grados/optica-y-optometria-terrassa-foot'),

]

URL_UPC = 'https://www.upc.edu/aprender/estudios/{0}'